FROM openjdk
COPY target/Transaccion-01.jar Transaccion.jar
ENTRYPOINT ["java", "-jar", "/Transaccion.jar"]

#docker build -t springtransaccion .
#docker run --name springtrasnaccioncontaier -p 8080:8080 -d springtransaccion